include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener torabo-caps torabo-rpc-tunnel torabo-timing torabo-live-feed torabo-trackball torabo-macros torabo-combos torabo-reserved-layers"
    cmake-args: -DDTS_EXTRA_CPPFLAGS="-DTORABO_RESERVED_LAYERS=10"
    artifact-name: torabo_tsuki_lp_right_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "studio-rpc-usb-uart torabo-timing-split"
    artifact-name: torabo_tsuki_lp_left_peripheral
  - board: bmp_boost
    shield: settings_reset
